import styles from '../styles/Home.module.css'
import { RedeNeural } from '../components/rede-neural'
import { RNPerceptron } from '../components/perceptron'
import Head from 'next/head'

export default function Home() {
  // feedforward

  const config = {
    inputs: [0, 1],
    target: 1,
    epochs: 300,
    activation: 'tanh',
  }
  const neuronio = new RedeNeural()
  neuronio.train(config)
  neuronio.feedforward()

  // perceptron

  const treinar = [
    {input: [0, 0], output: [0]},
    {input: [0, 1], output: [1]},
    {input: [1, 0], output: [1]},
    {input: [1, 1], output: [0]}
  ]

  const neuronio2 = new RNPerceptron();
  neuronio2.train(treinar);
  const result  = neuronio2.predict([0, 0]);
  const result2  = neuronio2.predict([0, 1]);
  const result3  = neuronio2.predict([1, 0]);
  const result4  = neuronio2.predict([1, 1]);

  console.log(`0 xor 0: ${result}, 0 xor 1: ${result2}, 1 xor 0: ${result3}, 1 xor 1: ${result4}`)

  // network

  const params = {
    input_nodes: 2,
    hidden_nodes: 4,
    output_nodes: 1,
    epochs: 40000,
    learning_rate: 0.5
  };

  /*const input = math.matrix([[0, 0], [0, 1], [1, 0], [1, 1]]);
  const target = math.matrix([[0], [1], [1], [0]])

  const neuronio3 = new NeuralNetwork(params);
  neuronio3.train(input, target);

  const prever  = parseFloat(neuronio3.predict([0, 0]._data)).toFixed(4);
  const prever2  = parseFloat(neuronio3.predict([0, 1]._data)).toFixed(4);
  const prever3  = parseFloat(neuronio3.predict([1, 0]._data)).toFixed(4);
  const prever4  = parseFloat(neuronio3.predict([1, 1]._data)).toFixed(4);

  console.log(`0 xor 0: ${prever}, 0 xor 1: ${prever2}, 1 xor 0: ${prever3}, 1 xor 1: ${prever4}`);*/

  return (
    <div className={styles.container}>
      <Head>
        <title>Deep learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}